import type { Post } from "./posts-types";
import { images } from "./images";

const posts: Post[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. Laser vs Plasma
  // ─────────────────────────────────────────────────────────────
  {
    slug: "debitare-laser-vs-plasma",
    title: "Debitare laser vs plasma: care este diferența și când alegi fiecare?",
    description:
      "Comparație directă debitare laser CNC vs plasma CNC: toleranțe, finisaj, materiale, costuri. Ghid tehnic pentru cumpărători B2B.",
    metaTitle: "Debitare laser vs plasma: ghid comparație 2026 | SOZO PROJECT",
    metaDescription:
      "Comparație completă debitare laser CNC vs plasma CNC: toleranțe, materiale, costuri, aplicații. Ghid tehnic pentru cumpărători B2B din industrie.",
    datePublished: "2026-05-09",
    dateModified: "2026-05-16",
    readMin: 6,
    hero: images.heroLaser,
    heroAlt: "Comparație debitare laser CNC vs plasma CNC — atelier industrial",
    category: "Tehnic",
    body: [
      { type: "p", text: "Pentru orice piesă tăiată din tablă există două tehnologii principale care concurează direct: debitarea laser CNC și debitarea plasma CNC. Alegerea greșită nu e o catastrofă, dar costă — fie în precizie, fie în bani, fie în timp. Acest ghid îți spune când alegi fiecare metodă, pe baza specificațiilor reale ale piesei tale, nu a vorbei vânzătorului." },
      { type: "h2", text: "Ce este debitarea laser CNC?" },
      { type: "p", text: "Debitarea laser folosește un fascicul de lumină concentrată — la laserul CO2, generat printr-un amestec de gaze excitat electric, cu o putere de 4–6 kW — pentru a topi și vaporiza local materialul, urmat de un jet de gaz (azot sau oxigen) care evacuează topitura. Rezultatul: o tăietură cu lățime sub 0.3 mm, marginile curate, fără bavuri pe majoritatea grosimilor uzuale, și toleranțe poziționale tipic de ±0.05–0.1 mm." },
      { type: "p", text: "Mașinile moderne, cum e Mitsubishi ML3015EX cu care lucrăm noi, au repetabilitate ±0.02 mm — adică piesa numărul 100 din serie iese identică cu prima. Asta contează când livrezi în industria automotive sau medicală, unde două piese diferite înseamnă două lucrări de control respinse." },
      { type: "h2", text: "Ce este debitarea plasma?" },
      { type: "p", text: "Plasma folosește un arc electric ionizat printr-un jet de gaz pentru a tăia metalul — temperatura plasma-ului ajunge la ~30.000 °C și topește practic orice material conductiv, inclusiv tablă groasă. Mașinile moderne cu plasma de înaltă definiție (HD plasma) ajung la toleranțe de ±0.5–1 mm și o zonă afectată termic mai mică decât plasma clasică, dar tot mai mare decât laser." },
      { type: "p", text: "Avantajul plasma: cost mai mic per oră de funcționare, capacitate ușoară de a tăia tablă foarte groasă (peste 25 mm), și mașini mai ieftine ca investiție. Dezavantajul: tăieturile sunt mai late (kerf 1.5–4 mm), suprafețele au reziduuri (slag) care necesită rectificare, și piesele mici cu contururi fine devin imprecise." },
      { type: "h2", text: "Comparație directă pe puncte critice" },
      {
        type: "table",
        head: ["Criteriu", "Laser CNC", "Plasma CNC"],
        rows: [
          ["Toleranță pozițională", "±0.05–0.1 mm", "±0.5–1 mm"],
          ["Lățime tăietură (kerf)", "0.2–0.3 mm", "1.5–4 mm"],
          ["Finisaj margine", "Curat, fără bavuri", "Slag, necesită rectificare"],
          ["Grosime optimă", "1–20 mm", "5–50 mm"],
          ["Inox / aluminiu", "Excelent", "Acceptabil (HD plasma)"],
          ["Cost per piesă (subțire)", "Mic — viteză mare", "Mare — kerf risipește material"],
          ["Cost per piesă (gros >20mm)", "Mare — viteza scade", "Mic — viteza rămâne ridicată"],
          ["Detalii fine, găuri mici", "Imposibil de bătut", "Limitate (kerf mare)"],
        ],
      },
      { type: "h2", text: "Când alegi laserul?" },
      { type: "ul", items: [
        "Piese cu contururi fine, găuri mici (sub 5 mm diametru), text gravat sau decupat",
        "Toleranțe sub ±0.2 mm pe orice cotă critică",
        "Tablă subțire (1–10 mm) — laserul e mai rapid și mai ieftin pe această zonă",
        "Inox sau aluminiu unde finisajul margine contează (decorativ, alimentar, optic)",
        "Serii repetabile unde piesa 1 și piesa 1000 trebuie identice",
        "Componente care intră în asamblare automată (toleranțele determină dacă montajul „prinde”)",
      ]},
      { type: "h2", text: "Când alegi plasma?" },
      { type: "ul", items: [
        "Tablă groasă peste 20–25 mm de oțel structural",
        "Piese mari, cu toleranțe relaxate (±1 mm e OK pentru aplicația ta)",
        "Construcții metalice grele, structuri de susținere, grinzi",
        "Buget strict pentru o lucrare unică, nerecurentă, fără cerințe estetice",
      ]},
      { type: "callout", text: "Greșeala clasică: alegi plasma pentru că e mai ieftină per oră, dar piesa ta cere ±0.1 mm. Rezultatul: rectificări manuale, întârzieri, și un cost final mai mare decât laserul de la început." },
      { type: "h2", text: "Și frezarea? Și ștanțarea?" },
      { type: "p", text: "Frezarea CNC e o altă alternativă pentru piese 2D din tablă, dar e dramatic mai lentă decât laserul și costă mai mult per piesă pentru forme complexe. Avantajul ei rămâne pe piese 3D sau pe materiale care nu se pot tăia termic (anumite plastice tehnice, cupru gros). Pentru tablă plată — laserul aproape întotdeauna câștigă." },
      { type: "p", text: "Ștanțarea e excelentă în serie mare (peste 5.000 buc) când investești într-o matriță. Dar matrița costă 5.000–50.000 € și nu se amortizează pe serii mici. Pentru orice serie sub 1.000 piese, laserul e mai ieftin de la primul lot." },
      { type: "h2", text: "Concluzie — ce oferim noi" },
      { type: "p", text: "La SOZO PROJECT lucrăm exclusiv cu debitare laser CNC pentru că aici se află nișa unde precizia, viteza și flexibilitatea coincid. Echipamentul nostru — Mitsubishi ML3015EX, CO2 4.5 kW — taie oțel până la 20 mm, inox/aluminiu până la 10 mm, cu ±0.05 mm pozițional. Pentru tablă mai groasă sau aplicații unde toleranța nu contează, te trimitem onest către un atelier de plasma. Asta e parte din consultanța inclusă." },
      { type: "internal", href: "/servicii/debitare-laser", label: "Vezi serviciul de debitare laser", text: "Specificații complete, materiale acceptate, format fișiere — pe pagina serviciului." },
    ],
    faqs: [
      { q: "Care metodă e mai rapidă, laser sau plasma?", a: "Pentru tablă subțire (sub 10 mm) laserul CO2 e mai rapid decât plasma. Peste 20 mm, plasma poate fi mai rapidă, dar la costul calității finisajului." },
      { q: "Pot să combin metodele pe aceeași piesă?", a: "Tehnic da — multe ateliere de plasma rectifică margini ulterior. Practic, pentru piese cu cerințe de precizie, e mai ieftin să alegi laser de la început decât să rectifici manual." },
      { q: "Care metodă e mai sustenabilă?", a: "Laserul CO2 e mai eficient per piesă pe tablă subțire față de plasmă — viteza de tăiere mai mare înseamnă mai puțin timp activ per piesă. Plasma consumă mai mult energie pe tablă sub 10 mm din cauza vitezei mai mici." },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 2. Tolerante
  // ─────────────────────────────────────────────────────────────
  {
    slug: "tolerante-debitare-laser",
    title: "Ce toleranțe oferă debitarea laser? Ghid tehnic complet 2026",
    description:
      "Toleranțe pozitionale, dimensionale și unghiulare pentru debitarea laser CNC pe oțel, inox, aluminiu. Date reale Mitsubishi ML3015EX.",
    metaTitle: "Toleranțe debitare laser CNC — ghid tehnic 2026 | SOZO PROJECT",
    metaDescription:
      "Toleranțe standard și de precizie pentru debitare laser CNC pe oțel, inox, aluminiu. Date reale de la Mitsubishi ML3015EX. Cum specifici corect în desen.",
    datePublished: "2026-05-09",
    dateModified: "2026-05-16",
    readMin: 7,
    hero: images.precisionEdge,
    heroAlt: "Detaliu margine debitată laser pe inox 304 — toleranță ±0.05mm",
    category: "Tehnic",
    body: [
      { type: "p", text: "„Ce toleranță aveți la laser?” — întrebarea pe care o primim cel mai des. Răspunsul scurt: ±0.05 mm pozițional, ±0.02 mm repetabilitate. Răspunsul lung explică de ce diferența contează, ce înseamnă pentru piesa ta concretă, și cum să specifici corect toleranțele în desen ca să nu plătești pentru precizie de care nu ai nevoie." },
      { type: "h2", text: "Toleranță pozițională vs dimensională vs repetabilitate" },
      { type: "p", text: "Trei concepte care se confundă des, dar înseamnă lucruri diferite în practică:" },
      { type: "ul", items: [
        "Toleranță pozițională — cât de exact poate mașina să poziționeze capul laser pe planul X-Y. La Mitsubishi ML3015EX: ±0.05 mm pe 500 mm cursă.",
        "Toleranță dimensională — cât de aproape de cota din desen iese piesa fizică. Influențată de poziționare + lățimea tăieturii (kerf) + dilatare termică. Tipic ±0.1 mm.",
        "Repetabilitate — dacă tăiem aceeași piesă de 100 de ori, cât de mult variază. La noi: ±0.02 mm. Asta înseamnă că serie e uniformă, nu doar o piesă noroc.",
      ]},
      { type: "callout", text: "În practică: dacă ai o gaură ∅10 mm cu toleranță ±0.05 mm, te interesează și poziționarea (centrul găurii pe corect), și dimensiunea (10.00 mm fix), și repetabilitatea (toate piesele la fel)." },
      { type: "h2", text: "Toleranțe tipice per material și grosime" },
      { type: "p", text: "Cu cât tabla e mai groasă, cu atât toleranțele cresc — efect termic mai mare, conicitatea tăieturii (taper) mai pronunțată. Iată valorile realiste pe Mitsubishi ML3015EX:" },
      {
        type: "table",
        head: ["Material", "Grosime", "Toleranță standard", "Toleranță precizie"],
        rows: [
          ["Oțel carbon", "≤ 6 mm", "±0.1 mm", "±0.05 mm"],
          ["Oțel carbon", "6–12 mm", "±0.15 mm", "±0.1 mm"],
          ["Oțel carbon", "12–20 mm", "±0.2 mm", "±0.15 mm"],
          ["Inox 304/316", "≤ 6 mm", "±0.1 mm", "±0.05 mm"],
          ["Inox 304/316", "6–10 mm", "±0.15 mm", "±0.1 mm"],
          ["Aluminiu", "≤ 5 mm", "±0.1 mm", "±0.05 mm"],
          ["Aluminiu", "5–10 mm", "±0.15 mm", "±0.1 mm"],
        ],
      },
      { type: "p", text: "„Standard” e ce primești implicit, fără cerere expresă. „Precizie” e ce putem garanta dacă marchezi cota ca fiind critică în desen — implică verificare suplimentară pe piesa finală și, eventual, ajustare de proces." },
      { type: "h2", text: "Factori care influențează toleranța reală" },
      { type: "ol", items: [
        "Grosimea materialului — mai gros = toleranțe mai relaxate. Pe 20 mm oțel nu vei avea ±0.05 mm, indiferent de mașină.",
        "Calitatea tablei — tabla de stoc cu rugozitate sau ondulații afectează prima cotă a piesei (deformare termică).",
        "Numărul de cote critice pe piesă — cu cât mai multe contururi precise, cu atât crește riscul cumulativ; e bine să marchezi care sunt critice și care relaxate.",
        "Dimensiunea piesei — pe piese mari (>1500 mm), poziționarea relativă poate avea ușoară deviație termică pe parcursul tăierii.",
        "Forma — găurile foarte mici (sub diametrul materialului) nu pot fi tăiate la cotă exactă fără strategii speciale de pierce.",
      ]},
      { type: "h2", text: "Cum specifici toleranțele în desen" },
      { type: "p", text: "Cea mai mare problemă în desenele primite: clientul cere implicit ±0.05 mm pe toate cotele. Rezultă cost mărit (verificare + posibilă rectificare) pentru cote care, în realitate, n-aveau nevoie de atâta precizie. Recomandare practică:" },
      { type: "ul", items: [
        "Marchează explicit doar cotele critice (de exemplu, gauri pentru asamblare automată, suprafețe de etanșare).",
        "Pentru cotele non-critice, indică ISO 2768-mK (toleranțe generale medii) sau ±0.5 mm — e suficient pentru contururi exterioare ne-funcționale.",
        "Dacă piesa intră în prelucrare ulterioară (frezare finală, găurire), specifică „dimensiune brut” + adaos de prelucrare în desen.",
      ]},
      { type: "h3", text: "Exemplu concret" },
      { type: "p", text: "O piesă de 200×150 mm, oțel 4 mm, cu 4 găuri ∅8.5 mm pentru șurub M8. Doar găurile sunt critice (montaj). Conturul exterior poate avea ±0.5 mm. Specificare corectă:" },
      { type: "ul", items: [
        "Cote contur exterior: ISO 2768-mK (sau ±0.5 mm)",
        "Diametre găuri ∅8.5 +0.05 / -0.0",
        "Distanțe între centre găuri: ±0.1 mm",
      ]},
      { type: "p", text: "Costul piesei specificate corect e sensibil mai mic decât dacă ceri ±0.05 mm peste tot, fără justificare." },
      { type: "h2", text: "Ce putem garanta noi (Mitsubishi ML3015EX, date reale)" },
      { type: "ul", items: [
        "Pozițional: ±0.05 mm pe orice cursă sub 500 mm",
        "Repetabilitate: ±0.02 mm pe serii uniforme",
        "Toleranță contur: ±0.1 mm standard, ±0.05 mm la cerere pe materiale subțiri",
        "Toleranță gaură: ±0.05 mm pe diametre > grosimea materialului, ±0.03 mm pe materiale subțiri",
      ]},
      { type: "p", text: "Acestea nu sunt cifre de marketing — sunt măsurate prin control dimensional pe piese de probă, periodic, și pe piese de control la livrare când clientul cere first-article inspection report." },
      { type: "internal", href: "/servicii/debitare-laser", label: "Vezi specificațiile complete", text: "Toleranțe per material, formate fișier acceptate, proces de comandă." },
    ],
    faqs: [
      { q: "Care e diferența între ±0.05 și ±0.02 mm?", a: "±0.05 e poziționarea capului laser. ±0.02 e cât variază piesă-cu-piesă pe aceeași serie. Ambele contează." },
      { q: "Pot avea ±0.01 mm la laser?", a: "Nu pe materiale tipice. Pentru toleranțe sub ±0.05 mm pe cote critice, e nevoie de prelucrare ulterioară (frezare sau rectificare)." },
      { q: "Cum verific că piesa primită are toleranța promisă?", a: "Cere first-article inspection report la comandă. Măsurăm cotele critice cu echipament calibrat și îți trimitem raport." },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 3. DXF prep
  // ─────────────────────────────────────────────────────────────
  {
    slug: "cum-pregatesti-fisiere-dxf",
    title: "Cum pregătești fișierele DXF pentru debitare laser — ghid pas cu pas",
    description:
      "Ghid complet pentru pregătirea fișierelor DXF pentru debitare laser CNC. Layere, scara, contururi, erori frecvente de evitat.",
    metaTitle: "Cum pregătești fișiere DXF pentru debitare laser — ghid 2026 | SOZO PROJECT",
    metaDescription:
      "Ghid complet pentru pregătirea fișierelor DXF pentru debitare laser CNC. Layere, scara, contururi închise, erori frecvente. Checklist înainte de trimitere.",
    datePublished: "2026-05-09",
    dateModified: "2026-05-16",
    readMin: 8,
    hero: images.engineering,
    heroAlt: "Inginer pregătind fișier DXF pentru debitare laser în software CAD",
    category: "How-to",
    body: [
      { type: "p", text: "Un fișier DXF curat înseamnă ofertă rapidă, preț corect și piesă identică cu desenul. Un DXF prost îți întârzie comanda, generează costuri ascunse și uneori produce piese greșite. Acest ghid trece prin fiecare element pe care îl verificăm noi când primim un fișier — folosește-l ca pe un checklist înainte să trimiți." },
      { type: "h2", text: "Software-uri uzuale pentru DXF" },
      { type: "p", text: "Practic, orice CAD modern exportă DXF. În ordinea calității output-ului pe care o vedem în atelier:" },
      { type: "ul", items: [
        "AutoCAD — referință de fapt; exportă DXF curat dacă desenezi corect.",
        "SolidWorks — Save As → DXF din schiță. Atenție la layere și la blocuri convertite.",
        "Fusion 360 — Sketch → Right click → Save as DXF. Verifică unitățile (default poate fi inch).",
        "Inventor — similar cu SolidWorks.",
        "LibreCAD — gratuit, suficient pentru piese 2D simple.",
        "Onshape — export DXF din skicker.",
      ]},
      { type: "p", text: "Evită convertoarele online dubioase și PDF→DXF automat. Rezultatul are aproape întotdeauna linii duble, contururi deschise sau scară greșită." },
      { type: "h2", text: "Setări de bază: unitate, scară, format" },
      { type: "ol", items: [
        "Unitatea de măsură: milimetri. Dacă lucrezi în inch, convertește înainte de export. Toate atelierele de laser CNC din Europa folosesc mm.",
        "Scara: 1:1. Niciodată 1:10 sau 1:100. Conturul desenat 100 mm = 100 mm reali în fișier.",
        "Versiunea DXF: AutoCAD 2010 sau ulterioară. Versiunile mai vechi pierd anumite tipuri de entități.",
        "Codepage: ASCII sau UTF-8 dacă ai text (deși text-ul nu trebuie să fie pe layerul de tăiere).",
      ]},
      { type: "h2", text: "Structura layerelor" },
      { type: "p", text: "Aici se face diferența între un fișier amator și unul profesional. Conventia clasică:" },
      { type: "ul", items: [
        "Layer „CUT” (sau „Cut”, „Tăiere”) — toate liniile care trebuie tăiate de laser.",
        "Layer „ENGRAVE” (sau „Marcaj”) — linii care trebuie gravate, nu tăiate (de exemplu, numere de serie).",
        "Layer „FOLD” (sau „Pliere”) — pentru piese care urmează să fie îndoite la abkant; marchează liniile de îndoire fără să le tăiem.",
        "Layer „REFERINȚĂ” (sau orice alt nume) — pentru conturul brut, dimensiuni, note. Nu e tăiat.",
      ]},
      { type: "p", text: "Daca toate liniile sunt pe layerul „0” (default), avem două probleme: (1) nu știm care e contur și care e text, (2) trebuie să curăț noi fișierul, ce întârzie oferta. Investiția în 5 minute de organizare îți economisește o oră de comunicare cu noi." },
      { type: "h2", text: "Reguli pentru contururi" },
      { type: "ul", items: [
        "Toate contururile trebuie să fie închise. O linie deschisă cu 0.001 mm la capete = laser face o tăietură nedorită.",
        "Fără linii duble suprapuse. Două linii desenate pe aceeași poziție = laser le taie pe ambele, de două ori, riscând să ardă marginea.",
        "Polilinii preferate pentru contururi închise. Eliminei riscul de „nesfârșirea” conturului.",
        "Cercurile să fie cercuri reale (entitate CIRCLE), nu poligoane cu 32 de muchii.",
        "Curbele complexe (NURBS, splines) — convertește-le în polilinii sau arce. Multe controllere CNC nu citesc spline-uri direct.",
      ]},
      { type: "h2", text: "Greșeli frecvente și cum le eviți" },
      {
        type: "table",
        head: ["Greșeală", "Consecință", "Soluție"],
        rows: [
          ["Linii duble", "Tăiere dublă, margine arsă", "Comanda OVERKILL în AutoCAD înainte de export"],
          ["Contur deschis", "Piesă nu se decupează", "Comanda CLOSE pe poliline"],
          ["Text pe layer cut", "Laser taie literele", "Mută text pe layer separat"],
          ["Cotații în fișier", "Confuzie + tăiere greșită", "Layer „dim” separat sau elimină complet"],
          ["Scară greșită", "Piesa iese de 10× mai mică/mare", "Verifică o cotă cunoscută înainte de export"],
          ["Unități diferite", "Piesa la jumătate (inch→mm)", "Setează clar mm înainte de export"],
        ],
      },
      { type: "h2", text: "Cum verifici fișierul înainte să-l trimiți" },
      { type: "ol", items: [
        "Deschide DXF-ul într-un viewer separat (AutoCAD, LibreCAD, ViewCompanion, online viewers).",
        "Verifică scara — măsoară o cotă cunoscută cu unealta dimensională.",
        "Activează doar layerul de tăiere și verifică vizual că vezi toate contururile pe care le aștepți.",
        "Verifică contururile închise: poliline cu poziție start = poziție end.",
        "Asigură-te că nu ai entități în afara cadrului piesei (linii rătăcite, text uitat).",
      ]},
      { type: "callout", text: "Trucul nostru: dacă vezi piesa ta într-un viewer și o numeri în cap pas cu pas (1 contur exterior + 4 găuri = 5 elemente), știi că e curată. Dacă numeri 7 și aștepți doar 5, ai linii în plus." },
      { type: "h2", text: "Alternative: DWG, STEP, PDF" },
      { type: "ul", items: [
        "DWG — format AutoCAD nativ, mai bogat decât DXF. Acceptat de orice atelier serios.",
        "STEP / STP — format 3D. Util pentru piese cu cerințe de îndoire complexe sau pentru asamblări. Noi extragem geometria 2D din STEP automat.",
        "PDF cu cote — accept pentru ofertă, dar pentru producție avem nevoie de DXF (PDF-urile vectoriale au probleme cu liniile duble).",
      ]},
      { type: "h2", text: "Checklist final înainte de trimitere" },
      { type: "ul", items: [
        "Scara 1:1 în mm",
        "Layere clar denumite (cut / engrave / fold / reference)",
        "Contururi închise verificate",
        "Fără linii duble (run OVERKILL în AutoCAD)",
        "Fără text sau cote pe layerul de tăiere",
        "Cercurile sunt entități CIRCLE",
        "Splines convertite în polilinii dacă există",
        "Verificat într-un viewer extern",
      ]},
      { type: "p", text: "Dacă ai trecut toate punctele, fișierul e pregătit. Trimite-l pe WhatsApp sau prin formularul de ofertă — fișier clar înseamnă ofertă rapidă, de obicei în 2–4h." },
      { type: "internal", href: "/cere-oferta", label: "Trimite fișierul DXF acum", text: "Ai pregătit fișierul după checklist? Încarcă-l în formularul de ofertă — primești oferta în aceeași zi." },
    ],
    faqs: [
      { q: "Pot trimite DXF din Adobe Illustrator?", a: "Da, dar verifică unitățile (default e adesea points/inches) și convertește textul în path-uri. Atenție la linii duble — Illustrator generează des duplicate." },
      { q: "Ce fac dacă nu am DXF, doar PDF?", a: "Trimite PDF-ul cu dimensiuni pentru ofertă. Dacă confirmi comanda, putem extrage geometria din PDF (cost mic suplimentar) sau rea-desenăm fișierul pe baza cotelor tale." },
      { q: "Dimensiunile maxime acceptate?", a: "Tabla maximă: 3050 × 1525 mm. Piesa individuală poate fi orice dimensiune sub aceasta — încercăm să o încadrăm pe foaie." },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 4. Materiale
  // ─────────────────────────────────────────────────────────────
  {
    slug: "materiale-debitare-laser",
    title: "Materiale pentru debitare laser: oțel, inox, aluminiu — grosimi, toleranțe, sfaturi",
    description:
      "Ghid complet de materiale pentru debitare laser CNC: oțel carbon OL37/OL52, inox 304/316, aluminiu 5052/6061. Cum alegi materialul corect.",
    metaTitle: "Materiale debitare laser: oțel, inox, aluminiu — ghid complet | SOZO PROJECT",
    metaDescription:
      "Ghid complet de materiale pentru debitare laser CNC: oțel carbon OL37/OL52, inox 304/316, aluminiu 5052/6061. Grosimi maxime, toleranțe, recomandări per aplicație.",
    datePublished: "2026-05-09",
    dateModified: "2026-05-16",
    readMin: 8,
    hero: images.steelSheet,
    heroAlt: "Tablă oțel pregătită pentru debitare laser CNC, atelier industrial",
    category: "Tehnic",
    body: [
      { type: "p", text: "Trei familii de materiale acoperă peste 95% din debitarea laser industrială: oțel carbon, inox și aluminiu. Fiecare cu nuanțe care influențează cost, comportament la tăiere, toleranțe finale și aplicații recomandate. Ghidul de mai jos te ajută să alegi corect din prima — nu după primul lot eșuat." },
      { type: "h2", text: "Oțel carbon (OL37, OL52)" },
      { type: "p", text: "Calul de bătaie al fabricației metalice. Ieftin, bine standardizat, ușor de tăiat cu laser pe orice grosime tipică (1–20 mm). Două grade dominante:" },
      { type: "h3", text: "OL37 (S235JR)" },
      { type: "p", text: "Oțel structural de bază, rezistență la tracțiune ~360 MPa. Folosit pentru piese ne-critice ca sarcină: console, plăci de bază, panouri, suporți. Sudabil fără probleme. Acoperire vopsea sau zincare ulterioară posibilă fără tratamente speciale." },
      { type: "h3", text: "OL52 (S355JR)" },
      { type: "p", text: "Oțel cu rezistență mai ridicată (~470 MPa la tracțiune). Folosit unde piesa trebuie să suporte sarcini ciclice sau presiuni: structuri portante, componente automotive, atașamente echipamente agricole. Costă cu ~5–10% mai mult decât OL37, dar pe piese critice diferența e neglijabilă." },
      { type: "h3", text: "Aplicații tipice oțel carbon" },
      { type: "ul", items: [
        "Construcții metalice: gusete, plăci de bază, console, panouri",
        "Automotive aftermarket: suporți de montaj, scuturi termice, ranforsări",
        "Mobilă industrială: rame metalice, structuri rafturi",
        "Echipamente agricole: plăci de uzură (cu OL52 sau oțel anti-uzură ulterior tratat)",
      ]},
      { type: "h2", text: "Inox (304, 316, 430)" },
      { type: "p", text: "Inoxul costă 5–10× mai mult decât oțelul carbon, dar nu corodează, e estetic și rezistă chimic. Tăierea cu laser CO2 dă margine curată dacă folosești azot ca gaz de asistență — oxigenul oxidează marginea și lasă o dungă neagră caracteristică." },
      { type: "h3", text: "Inox 304" },
      { type: "p", text: "Cel mai folosit inox industrial. Excelent compromis între cost, rezistență la coroziune și sudabilitate. Folosit în industria alimentară (suprafețe cu contact alimentar), echipamente sanitare, chiuvete industriale, fațade decorative, mobilier urban inox." },
      { type: "h3", text: "Inox 316" },
      { type: "p", text: "Conține molibden, ce-i dă rezistență superioară la medii cu cloruri (apă marină, soluții saline, acid clorhidric diluat). Folosit în industria marină, chimică, farmaceutică și medicală. Costă cu ~30% mai mult decât 304." },
      { type: "h3", text: "Inox 430" },
      { type: "p", text: "Inox feritic (magnetic), mai ieftin decât 304. Folosit pentru aplicații decorative, electrocasnice, panouri de afișare. Atenție: nu e potrivit pentru exterior fără protecție." },
      {
        type: "table",
        head: ["Grad inox", "Grosime max", "Cost relativ", "Aplicații"],
        rows: [
          ["304", "10 mm", "1.0× (referință)", "Alimentar, decorativ, sanitar"],
          ["316", "10 mm", "1.3×", "Marin, chimic, medical"],
          ["430", "8 mm", "0.85×", "Decorativ interior, electrocasnice"],
        ],
      },
      { type: "h2", text: "Aluminiu (1050, 5052, 6061-T6)" },
      { type: "p", text: "Aluminiul taie bine cu laser CO2, dar reflectă mai mult decât oțelul, deci viteza scade față de oțel la aceeași grosime. Densitatea lui (2.7 g/cm³ vs 7.85 pentru oțel) îl face de 3× mai ușor — critic pentru auto, aerospațial, electronică portabilă." },
      { type: "h3", text: "Aluminiu 1050" },
      { type: "p", text: "Aproape pur (99.5% Al). Foarte moale, formabil ușor, dar slab structural. Folosit pentru carcase decorative, panouri reflectorizante, etichete." },
      { type: "h3", text: "Aluminiu 5052" },
      { type: "p", text: "Aliaj cu magneziu, cel mai bun raport cost-rezistență-corosiune pentru tablă. Folosit în carcase electronice, rezervoare, panouri auto, echipamente marine de mică adâncime." },
      { type: "h3", text: "Aluminiu 6061-T6" },
      { type: "p", text: "Aliaj cu magneziu și siliciu, tratabil termic („T6” = tratament termic specific). Cel mai rezistent dintre aliajele uzual disponibile la tablă. Folosit în structuri aerospațiale, rame biciclete, structuri industriale ușoare. Mai dificil de tăiat (mai dur, dilatare termică mai mare)." },
      { type: "h2", text: "Cum alegi materialul corect pentru proiectul tău" },
      { type: "ol", items: [
        "Începi cu funcția: ce face piesa? Suportă sarcini? Stă în mediu coroziv? Trebuie ușoară?",
        "Verifici constrângerile: temperatură de operare, sudură ulterioară, vopsire, contact alimentar.",
        "Compari cost vs durată de viață: oțelul vopsit costă mai puțin decât inoxul, dar pe 10 ani inoxul rămâne, vopseaua se duce.",
        "Verifici disponibilitatea grosimii: nu toate gradele se găsesc în orice grosime; uneori e mai practic să schimbi gradul decât să aștepți import.",
      ]},
      { type: "h2", text: "Tabel comparativ complet" },
      {
        type: "table",
        head: ["Material", "Grosime max laser", "Densitate", "Coroziune", "Sudabilitate", "Cost relativ"],
        rows: [
          ["OL37", "20 mm", "7.85 g/cm³", "Slabă (necesită protecție)", "Excelentă", "1×"],
          ["OL52", "20 mm", "7.85 g/cm³", "Slabă", "Bună", "1.05×"],
          ["Inox 304", "10 mm", "8.0 g/cm³", "Bună", "Bună", "5–7×"],
          ["Inox 316", "10 mm", "8.0 g/cm³", "Excelentă", "Bună", "7–9×"],
          ["Aluminiu 5052", "10 mm", "2.68 g/cm³", "Bună", "Bună (TIG)", "3–4×"],
          ["Aluminiu 6061", "8 mm", "2.70 g/cm³", "Bună", "Acceptabilă", "3.5–4.5×"],
        ],
      },
      { type: "callout", text: "Sfat practic: dacă nu ești sigur, trimite-ne specificația aplicației (mediu, sarcini, durată) și recomandăm noi materialul. Consultanță inclusă în ofertă, fără cost suplimentar." },
      { type: "internal", href: "/servicii/debitare-laser", label: "Vezi specificațiile complete pentru debitare laser", text: "Materiale acceptate, grosimi maxime, toleranțe, formate fișier." },
    ],
    faqs: [
      { q: "Pot tăia cupru sau alamă cu laser?", a: "Tehnic da, dar reflectivitatea ridicată face tăierea grea pe materiale subțiri. Nu suntem specializați în acestea — recomandăm un atelier dedicat pentru cupru gros." },
      { q: "De ce inoxul costă atât de mult mai mult?", a: "Conținutul de crom (min 10.5%) și nichel (în 304/316) face ca aliajul să coste de câteva ori mai mult decât oțelul carbon." },
      { q: "Pot vopsi piesele de aluminiu după debitare?", a: "Da, dar e nevoie de tratament prealabil (eloxare sau primer special). Vopseaua direct pe aluminiu se descuamează." },
    ],
  },
  // ─────────────────────────────────────────────────────────────
  // 5. Piese de schimb industriale
  // ─────────────────────────────────────────────────────────────
  {
    slug: "piese-schimb-benzi-transportoare-tabla-cnc",
    title: "Piese de schimb pentru benzi transportoare și conveioare din tablă CNC",
    description:
      "De ce tabla CNC bate turnătoria pentru piese de schimb industriale: timp de livrare, precizie, cantitate minimă 1 buc. Ghid pentru ingineri de mentenanță.",
    metaTitle: "Piese de schimb benzi transportoare și conveioare — tablă CNC Iași | SOZO PROJECT",
    metaDescription:
      "Componente din tablă CNC pentru benzi transportoare, conveioare și echipamente industriale. Inginerie inversă, livrare rapidă, de la 1 bucată. Atelier Iași.",
    datePublished: "2026-05-17",
    readMin: 6,
    hero: images.portfolioIndustrialPart,
    heroAlt: "Piesă industrială din tablă oțel executată prin debitare laser CNC — componentă conveior",
    category: "Industrial",
    body: [
      { type: "p", text: "O linie de producție oprită costă. Nu în ore — în mii de euro pe oră. Când o piesă de pe banda transportoare cedează și stocul e zero, apar două opțiuni clasice: aștepți 4–6 săptămâni pentru o piesă turnată sau improvizezi. Există și o a treia opțiune, pe care inginerii de mentenanță o descoperă de obicei după prima urgență: tabla CNC." },
      { type: "h2", text: "De ce banda transportoare se oprește din cauza unei singure piese" },
      { type: "p", text: "Componentele din oțel ale unui conveior sau bandă transportoare se uzează neuniform. Plăcile de ghidaj, suporții laterali, flanșele de prindere și consolele portante sunt piesele cu uzură frecventă — sunt în contact direct cu materialul transportat, cu vibrații ciclice sau cu medii corozive. Producătorul original livrează cu un termen de 4–8 săptămâni, iar piesele de stoc sunt greu de justificat bugetar pentru echipamente cu zeci de variante." },
      { type: "h2", text: "Tabla CNC vs piesa turnată: comparație directă" },
      {
        type: "table",
        head: ["Criteriu", "Tablă CNC (laser + abkant)", "Piesă turnată / forjată"],
        rows: [
          ["Timp de livrare", "1–5 zile", "4–8 săptămâni"],
          ["Cantitate minimă", "1 bucată", "50–500 bucăți (amortizare matriță)"],
          ["Cost matriță / sculă", "Zero", "5.000–50.000 RON"],
          ["Modificare design", "Fișier nou — câteva ore", "Matriță nouă — săptămâni"],
          ["Toleranță", "±0.05–0.1 mm", "±0.5–2 mm (depinde de proces)"],
          ["Material disponibil", "OL37, OL52, inox 304/316, aluminiu", "Fontă, oțel turnat, aliaje speciale"],
        ],
      },
      { type: "p", text: "Concluzia practică: pentru piese plate sau profilate executabile din tablă, CNC-ul câștigă pe toate dimensiunile relevante pentru mentenanță — mai ales pe timp și flexibilitate." },
      { type: "h2", text: "Ce componente de conveior și bandă transportoare se pot executa din tablă" },
      { type: "p", text: "Regula simplă: dacă piesa originală e fabricată dintr-o singură bucată de tablă (eventual îndoită sau sudată), o putem replica. Componente uzuale:" },
      { type: "ul", items: [
        "Ghidaje laterale — plăci de ghidaj drepte sau profilate în U/L, oțel sau inox",
        "Suporți de prindere — console pentru rolele de retur, suporți motoare, prinderi structurale",
        "Plăci de uzură — plăci plate sau îndoite care preiau contactul cu materialul transportat; adesea în OL52 sau oțel anti-uzură",
        "Flanșe și plăci de montaj — pentru motoare, reductoare, role de tensionare",
        "Carcase de protecție — capace de tablă pentru a proteja angrenaje, lagăre sau zone de transfer",
        "Jgheaburi de ghidaj — pentru transport granule, praf sau materiale în vrac pe conveioare înclinate",
      ]},
      { type: "h2", text: "Materiale recomandate per aplicație" },
      {
        type: "table",
        head: ["Aplicație", "Material recomandat", "Motiv"],
        rows: [
          ["Ghidaje și suporți structurali", "Oțel OL52", "Rezistență mecanică, sudat ușor, ieftin"],
          ["Medii umede sau cu coroziune ușoară", "Inox 304", "Nu corodează, ușor de curățat"],
          ["Medii agresive (acid, saramură)", "Inox 316", "Rezistență chimică superioară cu molibden"],
          ["Plăci de uzură cu impact ridicat", "Oțel OL52 sau Hardox (la cerere)", "Duritate și rezistență la abraziune"],
          ["Aplicații unde masa contează", "Aluminiu 5052", "De 3× mai ușor decât oțelul"],
        ],
      },
      { type: "h2", text: "Inginerie inversă: aduci piesa, pleci cu replica" },
      { type: "p", text: "Cel mai frecvent scenariu în mentenanță: piesa s-a rupt, desenul tehnic nu există sau e pierdut, furnizorul original nu mai e activ. Procesul la SOZO PROJECT:" },
      { type: "ol", items: [
        "Aduci sau trimiți piesa originală (sau ce a rămas din ea)",
        "Măsurăm complet cu instrumentar calibrat — cote, raze, grosime, găuri",
        "Creăm fișierul de producție (DXF + detalii de îndoire dacă e cazul)",
        "Confirmi fișierul înainte de tăiere",
        "Executăm și livrăm — de regulă în 1–3 zile lucrătoare",
      ]},
      { type: "callout", text: "Dacă piesa e ruptă sau deformată, măsurăm porțiunile intacte și reconstruim geometric restul. Pe piese simetrice, o jumătate e suficientă." },
      { type: "h2", text: "Timp de execuție pentru urgențe industriale" },
      { type: "p", text: "Urgențele industriale au prioritate în programul nostru de producție. Piesă simplă (contur 2D, fără îndoiri complexe) cu fișier DXF gata: aceeași zi în majoritatea cazurilor. Piesă cu inginerie inversă: 24–48h. Pentru situații critice — linie de producție oprită, schimb de noapte — contactați-ne direct pe WhatsApp: răspundem în câteva minute și confirmăm disponibilitatea imediat." },
      { type: "h2", text: "Cât costă față de piesa originală?" },
      { type: "p", text: "Prețul depinde de dimensiunea piesei, grosimea tablei și complexitate. Ca referință: o placă de ghidaj standard 200×400 mm în oțel 6 mm cu 4 găuri costă 80–150 RON + TVA. O consolă simplă în L, oțel 4 mm: 60–100 RON + TVA. La piese urgente se adaugă o suprataxă de prioritate (10–20%). Ofertă exactă în 2–4h după trimiterea fișierului sau fotografiei piesei." },
      { type: "internal", href: "/servicii/piese-industriale-la-comanda", label: "Serviciul complet — piese industriale la comandă", text: "Materiale acceptate, proces detaliat, FAQ și CTA direct." },
    ],
    faqs: [
      { q: "Ce componente din conveioare și benzi transportoare puteți replica din tablă?", a: "Ghidaje laterale, suporți de prindere, plăci de uzură, flanșe, console, carcase de protecție, jgheaburi — orice componentă structurală sau de ghidaj executabilă dintr-o singură bucată de tablă, cu sau fără îndoiri." },
      { q: "Puteți executa piesa dacă am doar piesa veche, fără desen tehnic?", a: "Da. Aduceți piesa originală (sau fragmentele ei), o măsurăm complet și creăm fișierul de producție. Serviciu de inginerie inversă inclus fără cost adițional pentru piese simple." },
      { q: "Cât durează execuția unei piese urgente?", a: "Piesă simplă cu fișier DXF gata: aceeași zi la confirmare. Cu inginerie inversă: 24–48h. Contactați-ne pe WhatsApp pentru urgențe — confirmare disponibilitate în câteva minute." },
      { q: "Inox sau oțel pentru conveioare în mediu umed?", a: "Inox 304 pentru medii umede generale (alimente, produse chimice de curățare). Inox 316 pentru medii cu cloruri, acid sau saramură. Oțelul carbon e potrivit doar în medii uscate sau dacă se vopsește/zincează ulterior." },
    ],
  },
  // ─────────────────────────────────────────────────────────────
  // 6. Raza de îndoire
  // ─────────────────────────────────────────────────────────────
  {
    slug: "raza-indoire-tabla-tabel-materiale-grosimi",
    title: "Raza de îndoire pentru tablă: tabel complet pe materiale și grosimi",
    description:
      "Tabel complet cu raze minime de îndoire pentru oțel, inox și aluminiu. Formula r_min, K-factor, efectul direcției față de fibra tablei și exemple de calcul blank.",
    metaTitle: "Raza de îndoire tablă — tabel complet materiale și grosimi | SOZO PROJECT",
    metaDescription:
      "Raze minime de îndoire pentru oțel carbon, inox 304/316 și aluminiu 5052/6061. Tabel complet, formula K-factor și calcul blank. Referință tehnică pentru designeri și ingineri.",
    datePublished: "2026-05-17",
    readMin: 7,
    hero: images.portfolioBendingProfile,
    heroAlt: "Profile metalice îndoite la abkant CNC — exemplu raze de îndoire tablă oțel",
    category: "Tehnic",
    body: [
      { type: "p", text: "Raza de îndoire e unul dintre parametrii care determină dacă o piesă se poate executa sau nu. Dacă desenul specifică o rază mai mică decât minimul tehnic pentru materialul și grosimea aleasă, tabla crăpă sau se subțiază excesiv la îndoire. Articolul de față centralizează valorile de referință pentru materialele pe care le procesăm, plus formula de calcul pentru lungimea blankului." },
      { type: "h2", text: "Ce este raza de îndoire și de ce are o limită minimă" },
      { type: "p", text: "Raza de îndoire (r) este raza măsurată la interiorul îndoiturii. Când îndoim tabla, materialul de pe fața interioară se comprimă, iar cel de pe fața exterioară se întinde. Sub o anumită rază, întinderea exterioară depășește limita de rupere a materialului și apar fisuri. Limita e influențată de trei factori: materialul (ductilitatea lui), grosimea tablei și direcția îndoiturii față de fibra laminării." },
      { type: "h2", text: "Formula de bază: r_min = k × t" },
      { type: "p", text: "Raza minimă absolută se calculează simplu: r_min = k × t, unde t este grosimea tablei în mm și k este un coeficient specific materialului." },
      {
        type: "table",
        head: ["Material", "Coeficient k (față de fibră)", "Coeficient k (transversal)"],
        rows: [
          ["Oțel carbon moale OL37 / DC01", "0.5×t", "0.4×t"],
          ["Oțel carbon semidur OL52 / S355", "0.8×t", "0.6×t"],
          ["Inox 304 / 1.4301", "1.0×t", "0.8×t"],
          ["Inox 316 / 1.4401", "1.0×t", "0.8×t"],
          ["Aluminiu 5052-H32", "0.8×t", "0.6×t"],
          ["Aluminiu 6061-T6", "2.0×t", "1.5×t"],
          ["Oțel Corten (S355J2W)", "0.8×t", "0.6×t"],
        ],
      },
      { type: "callout", text: "Valorile de mai sus sunt raze minime absolute. În practică, folosim r ≥ 1×t ca valoare de lucru pentru oțel moale și r ≥ 1.5×t pentru inox — oferă o marjă de siguranță și reduce uzura sculei." },
      { type: "h2", text: "Tabel raze minime recomandate — oțel carbon (OL37 / OL52 / DC01)" },
      {
        type: "table",
        head: ["Grosime t (mm)", "r_min absolut (mm)", "r recomandat lucru (mm)", "Observații"],
        rows: [
          ["1.0", "0.5", "1.0", "—"],
          ["1.5", "0.8", "1.5", "—"],
          ["2.0", "1.0", "2.0", "—"],
          ["3.0", "1.5", "3.0", "—"],
          ["4.0", "2.0", "4.0", "—"],
          ["5.0", "2.5", "5.0", "—"],
          ["6.0", "3.0", "6.0", "—"],
          ["8.0", "4.0", "8.0", "La tablă > 6mm, verificați sculele disponibile"],
          ["10.0", "6.0", "10.0", "Forță mare necesară — verificați prealabil"],
          ["12.0", "8.0", "14.0", "Limita presei 160T depinde de lungimea îndoiturii"],
        ],
      },
      { type: "h2", text: "Tabel raze minime recomandate — inox 304 / 316" },
      {
        type: "table",
        head: ["Grosime t (mm)", "r_min absolut (mm)", "r recomandat lucru (mm)", "Observații"],
        rows: [
          ["1.0", "1.0", "1.5", "Inoxul ecruisează — nu forțați sub r_min"],
          ["1.5", "1.5", "2.0", "—"],
          ["2.0", "2.0", "3.0", "—"],
          ["3.0", "3.0", "4.5", "—"],
          ["4.0", "4.0", "6.0", "—"],
          ["5.0", "5.0", "7.5", "—"],
          ["6.0", "6.0", "9.0", "—"],
          ["8.0", "8.0", "12.0", "Verificați disponibilitate sculă V-larg"],
        ],
      },
      { type: "h2", text: "Tabel raze minime recomandate — aluminiu 5052 și 6061" },
      {
        type: "table",
        head: ["Material", "Grosime t (mm)", "r_min absolut (mm)", "r recomandat (mm)"],
        rows: [
          ["5052-H32", "1.0", "0.8", "1.0"],
          ["5052-H32", "1.5", "1.2", "1.5"],
          ["5052-H32", "2.0", "1.6", "2.0"],
          ["5052-H32", "3.0", "2.5", "3.0"],
          ["5052-H32", "4.0", "3.2", "4.0"],
          ["5052-H32", "5.0", "4.0", "5.0"],
          ["6061-T6", "1.0", "2.0", "2.5"],
          ["6061-T6", "1.5", "3.0", "4.0"],
          ["6061-T6", "2.0", "4.0", "5.0"],
          ["6061-T6", "3.0", "6.0", "8.0"],
          ["6061-T6", "4.0", "8.0", "10.0"],
        ],
      },
      { type: "callout", text: "6061-T6 e aliajul de aluminiu cu duritate ridicată — ductilitate semnificativ mai mică față de 5052. Dacă designul cere raze mici pe aluminiu, specificați 5052 în loc de 6061." },
      { type: "h2", text: "Efectul direcției față de fibra tablei (rolling direction)" },
      { type: "p", text: "Tabla laminată are o direcție preferențială de curgere a granulelor metalice — fibra. Îndoind paralel cu fibra (față de direcția de laminare), riscul de fisurare e mai mare față de îndoirea transversală. Consecințe practice:" },
      { type: "ul", items: [
        "Îndoiri critice (raze mici față de grosime) → orientați îndoitura perpendicular pe direcția de laminare",
        "Piese cu îndoiri pe mai multe direcții → verificați că cel puțin îndoirile cu raza cea mai mică sunt transversale",
        "Aluminiu 6061-T6 → direcția contează mai mult ca la oțel; specificați-o explicit în desen dacă piesa e critică",
        "Inox 304 → ecruisarea face ca și îndoitura transversală să necesite raze mai mari față de oțelul moale",
      ]},
      { type: "h2", text: "K-factor și calculul lungimii blankului" },
      { type: "p", text: "K-factor (K) definește poziția axei neutre față de grosimea tablei. Axa neutră e zona din secțiunea transversală unde materialul nu e nici comprimat, nici întins. Formula pentru lungimea de desfășurare (bend allowance, BA) la un unghi α:" },
      { type: "p", text: "BA = (π / 180) × α × (r + K × t)" },
      {
        type: "table",
        head: ["Material", "K-factor tipic"],
        rows: [
          ["Oțel carbon moale OL37 / DC01", "0.38"],
          ["Oțel carbon semidur OL52 / S355", "0.40"],
          ["Inox 304 / 316", "0.43"],
          ["Aluminiu 5052", "0.38"],
          ["Aluminiu 6061", "0.40"],
        ],
      },
      { type: "h2", text: "Exemplu practic de calcul blank" },
      { type: "p", text: "Piesă: profil în L din oțel OL37, grosime 3mm, r = 3mm, unghi 90°, flancuri: A = 50mm, B = 80mm." },
      { type: "ol", items: [
        "Bend allowance: BA = (π/180) × 90 × (3 + 0.38 × 3) = 1.5708 × 4.14 = 6.5mm",
        "Lungime blank = A + B + BA = 50 + 80 + 6.5 = 136.5mm",
        "Dacă r se schimbă la 5mm: BA = 1.5708 × (5 + 1.14) = 1.5708 × 6.14 = 9.6mm → blank 139.6mm",
      ]},
      { type: "p", text: "Concluzia practică: raza mai mare = blank mai lung. La piese cu multe îndoiri, diferența se acumulează și afectează dimensiunile finale. Dacă toleranțele sunt strânse (±0.5mm), specificați raza explicită în desen — nu lăsați atelierul să aleagă." },
      { type: "internal", href: "/servicii/prelucrare-abkant", label: "Serviciu prelucrare abkant CNC — specificații complete", text: "Grosimi maxime, materiale acceptate, toleranțe și FAQ pentru îndoire CNC." },
    ],
    faqs: [
      { q: "Care e raza minimă de îndoire pentru tablă de oțel 2mm?", a: "Raza minimă absolută pentru OL37 la 2mm este 1mm (0.5×t). Valoarea recomandată în producție este 2mm (1×t) — oferă marjă de siguranță și reduce uzura sculei." },
      { q: "Ce se întâmplă dacă îndoim sub raza minimă?", a: "Sub raza minimă, fața exterioară a îndoiturii se întinde peste limita de ductilitate a materialului. Rezultatul: fisuri superficiale sau rupere completă a tablei pe linia de îndoire. La inox și aluminiu 6061 riscul e mai mare față de oțelul moale." },
      { q: "De ce inoxul necesită raze mai mari decât oțelul carbon?", a: "Inoxul 304/316 ecruisează (se durifica) în zona de deformare — ductilitatea locală scade rapid sub efort. Limita de curgere a inoxului e mai ridicată decât a oțelului OL37, dar alungirea la rupere e mai mică în zona ecruisată. De aceea r_min ≈ 1×t față de 0.5×t la oțel moale." },
      { q: "Cum calculez lungimea blankului pentru o îndoire la 90°?", a: "Formula: BA = (π/180) × 90 × (r + K × t), unde K ≈ 0.38 pentru oțel moale. Exemplu: t=3mm, r=3mm → BA = 1.5708 × (3 + 1.14) = 6.5mm. Lungimea totală a blankului = suma flancurilor + BA pentru fiecare îndoire." },
    ],
  },
  // ─────────────────────────────────────────────────────────────
  // 7. Garduri din tablă debitată
  // ─────────────────────────────────────────────────────────────
  {
    slug: "garduri-tabla-debitata-custom",
    title: "Garduri din tablă debitată la comandă: de la fișier la produs finit",
    description:
      "Cum funcționează un gard din tablă debitată laser — materiale, patternuri, dimensiuni și pregătire fișier. Ghid complet pentru proprietari și designeri.",
    metaTitle: "Garduri din tablă debitată la comandă — Iași | SOZO PROJECT",
    metaDescription:
      "Garduri și panouri din tablă debitată laser la comandă în Iași: oțel zincat, Corten, inox. Orice pattern DXF/AI. De la 1 panou, ofertă în aceeași zi. ☎ +40 732 034 386",
    datePublished: "2026-05-17",
    readMin: 5,
    hero: images.portfolio4,
    heroAlt: "Panou decorativ din tablă inox tăiat laser CNC — exemplu gard metalic la comandă Iași",
    category: "Decorativ",
    body: [
      { type: "p", text: "Un gard din tablă debitată laser nu arată ca gardurile clasice. Nu are spalieri sudate, nu are ornamente turnate și nu are profile standard. Are un pattern ales de tine — geometric, organic, cu inițiale sau cu un motiv care se potrivește casei. Și totul pornește dintr-un fișier DXF." },
      { type: "h2", text: "Ce e un gard din tablă debitată și cum diferă de variantele clasice" },
      {
        type: "table",
        head: ["Tip gard", "Aspect", "Flexibilitate design", "Durabilitate"],
        rows: [
          ["Tablă debitată laser", "Pattern orice formă, finish modern", "Maximă — orice fișier DXF/AI", "Ridicată (zincat/inox/vopsit)"],
          ["Țeavă și profil sudat", "Geometric simplu, grilaj clasic", "Limitată — forme standard", "Ridicată"],
          ["Gard ornamental turnat", "Ornamente clasice", "Mică — cataloage de tipare", "Ridicată"],
          ["Tablă plină", "Opac, industrial", "Minimă", "Ridicată"],
        ],
      },
      { type: "p", text: "Avantajul tablei debitate: obții orice pattern — inclusiv logo-ul firmei, un motiv floral, un design geometric parametric sau litere — dintr-un singur material, cu o singură operație de tăiere." },
      { type: "h2", text: "Materiale recomandate pentru garduri exterioare" },
      {
        type: "table",
        head: ["Material", "Finisaj recomandat", "Durabilitate exterior", "Observații"],
        rows: [
          ["Oțel carbon (OL37)", "Zincare + vopsire pulbere", "15–25 ani", "Cel mai comun — raport preț/durabilitate optim"],
          ["Oțel Corten (S355J2W)", "Patinat natural (fără finisaj)", "30–50 ani", "Culoare ruginie caracteristică, strat de oxid protector stabil"],
          ["Inox 304", "Periat sau lustruit", "25+ ani", "Rezistent la coroziune, aspect premium, fără întreținere"],
          ["Aluminiu", "Eloxat sau vopsit pulbere", "20+ ani", "Greutate redusă — ideal pentru porți batante mari"],
        ],
      },
      { type: "callout", text: "Cortenlul nu necesită vopsire. Se lasă să patineze natural timp de 6–18 luni și formează un strat de oxid stabil care oprește coroziunea în profunzime. Rezultat: textură brută, estetică industrială, durată de viață maximă." },
      { type: "h2", text: "Cum pregătești fișierul pentru un gard debitare laser" },
      { type: "p", text: "Fișierul e totul. Laserul taie exact ce e în fișier — nu interpolează, nu completează goluri, nu presupune intenții. Cerințe minime pentru un fișier corect:" },
      { type: "ul", items: [
        "Format: DXF sau DWG (recomandat), SVG, AI (Illustrator), sau PDF vectorial cu dimensiuni reale",
        "Scară 1:1 în milimetri — nu în inches, nu în procente",
        "Contururi închise — toate liniile trebuie să formeze contururi complete, fără segmente deschise",
        "Un singur layer de tăiere — fără cote, texte de descriere sau axe pe același layer",
        "Spațiu minim între decupaje: cel puțin egal cu grosimea tablei (ex: tablă 3mm → min 3mm între găuri adiacente)",
      ]},
      { type: "p", text: "Ai un pattern în Illustrator sau Corel? Exportează ca DXF sau SVG și trimite-l. Dacă nu ești sigur că fișierul e corect, trimite-l oricum — îl verificăm gratuit înainte de ofertă și îți spunem dacă e nevoie de ajustări." },
      { type: "h2", text: "Tipuri de patternuri și ce funcționează bine la tăiere" },
      { type: "ul", items: [
        "Geometric (grile, hexagoane, romburi, triunghiuri) — cel mai simplu de tăiat, structură rigidă după tăiere",
        "Organic (frunze, crengi, valuri) — funcționează bine dacă contururile rămase au min 8–10mm grosime la tablă de 2–3mm",
        "Text și litere — literele cu insule interioare (O, A, B, D, P) se taie cu microponți care se șlefuiesc ulterior sau se proiectează cu bare de legătură tip stencil",
        "Logo sau motiv complex — trimite fișierul vectorial, evaluăm structura și semnalăm dacă e nevoie de ajustări de fabricabilitate",
      ]},
      { type: "h2", text: "Dimensiuni și grosimi disponibile" },
      {
        type: "table",
        head: ["Parametru", "Valoare"],
        rows: [
          ["Dimensiune maximă panou dintr-o singură bucată", "3050 × 1525 mm"],
          ["Grosime recomandată garduri oțel/Corten exterior", "3–8 mm"],
          ["Grosime recomandată inox exterior", "2–5 mm"],
          ["Toleranță de tăiere", "±0.1 mm"],
          ["Spațiu minim între decupaje", "≥ grosimea tablei"],
        ],
      },
      { type: "p", text: "Panouri mai mari se execută din două sau mai multe bucăți cu îmbinare — specificați dimensiunea totală și propunem soluția constructivă." },
      { type: "h2", text: "Procesul la SOZO PROJECT: de la fișier la panou gata" },
      { type: "ol", items: [
        "Trimiți fișierul (DXF, AI, PDF) sau o schiță cu dimensiunile și materialul dorit",
        "Verificăm fișierul și semnalăm orice problemă de fabricabilitate — gratuit",
        "Primești oferta cu preț, material și termen (2–4h pentru fișiere clare)",
        "Confirmi comanda — avans sau credit pentru clienți recurenți",
        "Tăiem și controlăm dimensional",
        "Ridici din Strada Aviației 9, Iași sau livrăm prin curier în toată România",
      ]},
      { type: "internal", href: "/servicii/debitare-laser", label: "Specificații complete debitare laser CNC", text: "Materiale acceptate, grosimi maxime, toleranțe și formate de fișier acceptate." },
    ],
    faqs: [
      { q: "Acceptați fișiere din Illustrator sau Corel pentru garduri decorative?", a: "Da. Fișierele AI (Illustrator) și CDR (Corel) se pot converti direct în DXF pentru producție. Exportați ca DXF sau SVG și trimiteți — dacă fișierul nu e imediat compatibil, îl ajustăm și confirmăm înainte de tăiere." },
      { q: "Care e dimensiunea maximă a unui panou dintr-o singură bucată?", a: "3050 × 1525 mm — dimensiunea maximă a tablei pe care o procesăm. Panouri mai mari se execută din mai multe bucăți cu îmbinare — specificați dimensiunile finale și propunem soluția constructivă." },
      { q: "Ce material recomandați pentru un gard exterior cu întreținere minimă?", a: "Corten pentru aspect industrial-rustic fără niciun finisaj suplimentar — patinează natural și devine autoportant. Inox 304 pentru aspect premium fără întreținere. Oțel carbon zincat + vopsit pulbere pentru raportul preț/durabilitate optim." },
      { q: "Pot comanda un panou de probă înainte de comanda finală?", a: "Da. Dacă nu ești sigur de dimensiunile exacte sau de densitatea patternului, executăm o probă pe un panou mai mic (de obicei 300×300 sau 500×500 mm). Costul probei se deduce din comanda finală dacă continuați cu ea." },
    ],
  },
  // ─────────────────────────────────────────────────────────────
  // 8. Designer industrial × atelier CNC
  // ─────────────────────────────────────────────────────────────
  {
    slug: "cum-lucrezi-atelier-cnc-designer-industrial",
    title: "Cum lucrezi cu un atelier CNC dacă ești designer industrial",
    description:
      "Ghid practic pentru designeri, arhitecți și studenți la design: ce poate face un atelier CNC, cum pregătești brieful, ce fișier să trimiți și greșelile care costă timp și bani.",
    metaTitle: "Cum lucrezi cu un atelier CNC — ghid pentru designeri industriali | SOZO PROJECT",
    metaDescription:
      "Ghid complet pentru designeri industriali și arhitecți: brief corect, format fișier DXF/AI, toleranțe, greșeli comune la prima comandă CNC. Atelier Iași — de la 1 bucată.",
    datePublished: "2026-05-17",
    readMin: 7,
    hero: images.engineering,
    heroAlt: "Atelier CNC laser — vedere de ansamblu mașină de debitare și operator",
    category: "Ghid",
    body: [
      { type: "p", text: "Prima comandă la un atelier CNC e aproape întotdeauna mai complicată decât pare. Nu pentru că procesul e complex — ci pentru că designerii și inginerii de atelier vorbesc limbi diferite. Designerul gândește în formă și estetică; atelierul gândește în fișiere, material, toleranțe și timp de tăiere. Articolul de față traduce între cele două." },
      { type: "h2", text: "Ce poate face un atelier CNC pentru un designer — și ce nu poate" },
      { type: "p", text: "Un atelier de debitare laser și îndoire abkant poate executa orice piesă plată sau profilată (îndoită) care poate fi definită în 2D. Concret:" },
      { type: "ul", items: [
        "Piese tăiate din tablă cu orice formă de contur — geometric, organic, text, logo",
        "Profile îndoite la unghiuri precise: L, U, Z, hat section, forme personalizate",
        "Prototipuri și serii mici — de la 1 bucată",
        "Piese cu toleranțe de ±0.05–0.1mm",
        "Materiale: oțel carbon, inox 304/316, aluminiu 5052/6061, Corten",
      ]},
      { type: "p", text: "Ce NU poate face un atelier de tablă CNC standard:" },
      { type: "ul", items: [
        "Forme 3D complexe — suprafețe curbe libere necesită frezare multiax sau turnare",
        "Grosimi foarte mari — debitare laser are limite pe material (oțel max 20mm, inox max 10mm)",
        "Filetare, sudură sau tratamente de suprafață — de obicei subcontractate sau făcute în altă etapă",
        "Produse finite cu asamblare — atelierul livrează piese, nu ansambluri complete (de regulă)",
      ]},
      { type: "h2", text: "Cum pregătești brieful: ce trebuie să specifici obligatoriu" },
      { type: "p", text: "Un brief incomplet e cea mai frecventă cauză de întârzieri și costuri suplimentare. Atelierul nu poate presupune ce nu e scris. Lista minimă:" },
      {
        type: "table",
        head: ["Informație", "De ce contează", "Exemplu"],
        rows: [
          ["Dimensiunile exacte", "Prețul se calculează pe suprafața tablei și pe conturul de tăiere", "300 × 450 mm"],
          ["Materialul", "Preț, parametri de tăiere și finisaj diferă radical", "Inox 304"],
          ["Grosimea tablei", "Afectează raza de îndoire, forța necesară și toleranța", "2 mm"],
          ["Cantitatea", "La 1 buc vs 50 buc, prețul pe bucată diferă semnificativ", "3 buc prototip"],
          ["Toleranțele critice", "Dacă nu specifici, atelierul aplică toleranța standard (±0.1mm)", "±0.2mm pe alezaje"],
          ["Finisajul dorit", "Tăiat brut, șlefuit, vopsit, zincat — fiecare presupune alt flux", "Vopsire pulbere RAL 9005"],
          ["Termenul", "Urgențele au prioritate în programare și pot influența prețul", "Vineri la prânz"],
        ],
      },
      { type: "h2", text: "Ce format de fișier să folosești" },
      { type: "p", text: "Ordinea preferinței din perspectiva atelierului:" },
      { type: "ol", items: [
        "DXF sau DWG — standardul de facto pentru debitare laser 2D. Scară 1:1 în milimetri, contururi închise, un singur layer de tăiere",
        "SVG vectorial — acceptat direct din Illustrator sau Inkscape, util pentru pattern-uri decorative",
        "STEP / STP — pentru piese cu îndoiri complexe unde geometria 3D e necesară",
        "AI (Illustrator) sau CDR (Corel) — acceptat de multe ateliere după conversie",
        "PDF vectorial cu dimensiuni reale — ca ultimă opțiune; verificați că nu e rasterizat",
        "Foto sau schiță de mână — doar pentru estimare orientativă, nu pentru producție",
      ]},
      { type: "callout", text: "Regula de aur: trimite fișierul la scară 1:1 în milimetri. Cel mai frecvent motiv de reluare a comenzii e fișierul în inches sau la scară greșită — atelierul taie exact ce e în fișier." },
      { type: "h2", text: "Cum funcționează prețul la un atelier CNC" },
      { type: "p", text: "Prețul final include trei componente: material, timp de tăiere și programare CNC. Lucruri pe care mulți designeri nu le știu la prima comandă:" },
      { type: "ul", items: [
        "Prețul nu e 'pe metru pătrat' — conturul de tăiere contează la fel de mult ca suprafața. O piesă cu multe găuri mici costă mai mult decât una mare cu contur simplu, chiar la aceeași suprafață",
        "La piese unice, costul de programare se împarte pe 1 bucată — piesele simple rămân accesibile, piesele complexe pot fi surprinzător de scumpe per bucată",
        "De la 10 bucăți în sus, prețul pe bucată scade semnificativ — programarea se amortizează",
        "Urgențele costă mai mult — prioriotizarea în programul de producție are un cost",
        "Verificarea fișierului e gratuită — trimite fișierul înainte de confirmare, nu după",
      ]},
      { type: "h2", text: "6 greșeli comune ale designerilor la prima comandă CNC" },
      { type: "ol", items: [
        "Fișier fără grosime specificată — atelierul nu poate alege materialul în locul tău; prețul și comportamentul la îndoire depind de ea",
        "Raze interioare de 0 (colțuri vii) la piese îndoite — imposibil fizic; raza minimă e funcție de grosimea tablei și materialului",
        "Goluri mai mici decât grosimea tablei — laserul nu poate tăia un slot de 1mm în tablă de 2mm fără să topească marginile",
        "Design ignorând direcția de laminare — la aluminiu 6061-T6 sau inox, orientarea față de fibră poate face diferența dintre o piesă funcțională și una crăpată",
        "Nu specifică toleranțele critice — atelierul aplică toleranța standard; dacă ai alezaje pentru rulmenți sau îmbinări precise, specifică explicit",
        "Comandă prototip fără să ceară o probă sau verificare a fișierului — o iterație corectată înainte de tăiere e gratuită; re-tăierea după livrare nu e",
      ]},
      { type: "h2", text: "Întrebările bune pe care să le pui atelierului" },
      { type: "ul", items: [
        "'Verificați fișierul înainte de tăiere?' — un atelier serios face asta implicit",
        "'Care e raza minimă de îndoire pentru grosimea și materialul ales?' — răspunsul îți spune dacă designul e fabricabil",
        "'Pot vedea o bucată de material înainte de comandă?' — util dacă finisajul vizual e critic",
        "'Cum se schimbă prețul dacă măresc cantitatea la X bucăți?' — ajută la decizia de prototip vs serie mică",
        "'Care e termenul standard și ce înseamnă urgent?' — termenele variază mult între ateliere",
      ]},
      { type: "internal", href: "/servicii/elemente-decorative-metal", label: "Elemente decorative din metal la comandă", text: "Garduri Corten, panouri perforat, litere și semnalistică — orice pattern DXF/AI, de la 1 bucată." },
    ],
    faqs: [
      { q: "Ca designer, trebuie să știu să creez fișiere DXF?", a: "Nu neapărat. Dacă lucrezi în Illustrator, Corel sau Inkscape, exportul în SVG sau DXF e o opțiune din meniu. Dacă lucrezi în Fusion 360 sau SolidWorks, DXF-ul se exportă direct din sketch. Dacă nu ai niciun software CAD/vector, o schiță clară cu dimensiuni ne permite să creăm fișierul — contra unui mic cost de desenare." },
      { q: "Pot comanda un singur prototip înainte de seria finală?", a: "Da, fără cantitate minimă. Un prototip de 1 bucată are același proces ca o serie — singura diferență e că programarea CNC se amortizează pe o singură piesă, deci costul per bucată e mai mare. Recomandat înainte de orice serie > 20 bucăți." },
      { q: "Ce toleranțe pot obține pentru o piesă de design cu cerințe de asamblare?", a: "Debitare laser CO2: ±0.05–0.1mm pe contur. Îndoire abkant CNC: ±0.1° pe unghi, ±0.2mm pe dimensiunile rezultate. Dacă ai alezaje pentru rulmenți sau știfturi, specifică toleranța explicită în desen — atelierul poate optimiza parametrii de tăiere." },
      { q: "Care e diferența practică dintre debitare laser și frezare CNC?", a: "Laserul taie tablă plată din exterior spre interior — ideal pentru contururi 2D complexe, găuri, pattern-uri. Frezarea CNC îndepărtează material din bloc solid — necesară pentru forme 3D, adâncimi, cavități. Dacă piesa ta se poate descompune în table tăiate și eventual îndoite, laserul e mai rapid și mai ieftin." },
    ],
  },
];

export default posts;
export function getPostBySlug(slug: string) {
  return posts.find((p) => p.slug === slug);
}
export function getAllSlugs() {
  return posts.map((p) => p.slug);
}
